FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# kospa

Polls is a simple API allowing consumers to view polls and vote in them.

## Topics [/topics]

### List All Topics [GET]

+ Response 200 (application/json)

        [
            {
                "id": "TPC-000001",
                "description": "topic 1",
                "creator": "Juanjo",
                "date": "20/11/2006",
                "status": "answered"
            },
            {
                "id": "TPC-000002",
                "description": "topic 2",
                "creator": "Pepe",
                "date": "20/09/2006",
                "status": "pending"
            },
            {
                "id": "TPC-000003",
                "description": "topic 3",
                "creator": "Natalia",
                "date": "20/12/2006",
                "status": "open"
            },
            {
                "id": "TPC-000004",
                "description": "topic 4",
                "creator": "Juanjo",
                "date": "20/03/2006",
                "status": "answered"
            }
            
        ]
        
        
## Topic [/topic]
        
### Get a Topic [GET]

+ Response 200 (application/json)

        {
            "id": "TPC-000001",
            "description": "topic 1",
            "creator": "Juanjo",
            "date": "20/11/2006",
            "status": "answered",
            "questions": [
                {
                    "id": "QUEST-000001",
                    "description": "question 1",
                    "creator": "Juanjo",
                    "date": "20/11/2006",
                    "status": "answered"
                },
                {
                    "id": "QUEST-000002",
                    "description": "question 2",
                    "creator": "Pepe",
                    "date": "20/09/2006",
                    "status": "pending"
                },
                {
                    "id": "QUEST-000003",
                    "description": "question 3",
                    "creator": "Natalia",
                    "date": "20/12/2006",
                    "status": "open"
                },
                {
                    "id": "QUEST-000004",
                    "description": "question 4",
                    "creator": "Juanjo",
                    "date": "20/03/2006",
                    "status": "answered"
                }
                
            ]
           
        }

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }